### PR TITLE
Handling IE11

### PR DESCRIPTION
**Pull request by Bothan-tarot**
Hi Milan,

Thanks for your tool, very useful.

I made this fix so that IE can display the html video feed of your software.
Can you please consider it and generate a new exe ?

### CODE REVIEW

**Comment by gen2brain** [comment]
Hi,
Is this tested also on Chrome and Firefox?

**Comment by Bothan-tarot** [comment]
Yes, absolutely.

**Comment by gen2brain** [comment]
Thanks, merged. I cannot release it right now but in a few days.

**Comment by Bothan-tarot** [comment]
Thanks, let me know when you do it.

**Comment by Bothan-tarot** [comment]
Hi. Any news ?

**Pull request merged**
