### PR TITLE
bugfix + cleanup

### PR DESCRIPTION
**Pull request by RandomErrorMessage**
When I updated the modules I had issues with goost, so I replaced it with stdlib base64. I couldn't find much info on goost so I assume it's a drop in replacement.

### CODE REVIEW

**Comment by gen2brain** [comment]
goost is a drop-in replacement but written in assembler, it gives a good performance boost on amd64. Better to solve the issue with modules updates. Btw. if it is removed then socket_amd64.go is not necessary at all.

**Comment by RandomErrorMessage** [comment]
I've submitted a PR to goost base64 to fix a minor issue with build flags regarding arm64 support: https://github.com/libgoost/encoding-base64/pull/1/commits

**Comment by RandomErrorMessage** [comment]
Re-added goost after fixing upstream amd64 build bug. Please review this PR again.

**Comment by gen2brain** [comment]
Merged, thanks!

**Pull request merged**
